name: testaction

on:
  push:
    branches: [ feature/workflows ]
  pull_request:
    branches: [ master ]

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: A job to test the action
    steps:
    - uses: actions/checkout@v2

    - name: Execute xpath-action
      id: xpath
      uses: QwerMike/xpath-action@v1
      with:
        filename: ./.github/workflows/testng-results.xml
        expression: '//testng-results'

    - name: Get xpath result
      run: echo -e "Result from xpath-action:\n${{ steps.xpath.outputs.result }}"
