name: testaction

on:
  push:
    branches: [ feature/workflows ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: A job to test the action
    steps:
    - uses: actions/checkout@v2

    - name: Execute xpath-action
      id: xpath
      uses: QwerMike/xpath-action@v1
      with:
        filename: ./.github/workflows/cd_catalog.xml
        expression: '//CD'

    - name: Get xpath result
      run: echo -e "Result from xpath-action:\n${{ steps.xpath.outputs.result }}"
      
    - name: Get XML Data
      id: getxml
      uses: velivalab/sn-devops-junit-action@master
      with:
        xml-report-filename: ./.github/workflows/testng-results.xml
        
    - name: Get xml info
      run: echo -e "Result from sn-devops-junit-action:\n${{ steps.getxml.outputs.result }}"
