name: testaction

on:
  push:
    branches: [ feature/workflows ]
  pull_request:
    branches: [ master ]

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: A job to test the action
    steps:
    - uses: actions/checkout@v2

    - name: Execute xpath-action
      id: xpath
      uses: QwerMike/xpath-action@v1
      with:
        filename: ./.github/workflows/cd_catalog.xml
        expression: '//CD'

    - name: Get xpath result
      run: echo -e "Result from xpath-action:\n${{ steps.xpath.outputs.result }}"
      
    - name: Get XML Data
      id: getxml
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
        xml-file: ./.github/workflows/testng-results.xml
        xpath: '//testng-results'
        
    - name: Get xml info
      run: echo -e "Result from getxml-action:\n${{ steps.getxml.outputs.info }}"
