name: testaction

on:
  push:
    branches: [ feature/workflows ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: A job to test the action
    steps:
    - uses: actions/checkout@v2

    - name: Execute xpath-action
      id: xpath
      uses: QwerMike/xpath-action@v1
      with:
        filename: ./.github/workflows/cd_catalog.xml
        expression: '//CD'

    - name: Get xpath result
      run: echo -e "Result from xpath-action:\n${{ steps.xpath.outputs.result }}"
      
    - name: Register JUnit Test Summaries
      id: registerts
      uses: velivalab/sn-devops-junit-action@master
      with:
        devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
        devops-integration-user-pass: ${{ secrets.SN_DEVOPS_PASSWD }}
        instance-name: ${{ secrets.SN_INSTANCE_NAME }}
        tool-id: ${{ secrets.SN_ORCH_TOOL_ID }}
        context-github: ${{ toJSON(github) }}
        xml-report-filename: ./.github/workflows/testng-results.xml
        
    - name: Display Register JUnit Test Summaries Result
      run: echo -e "Result from sn-devops-junit-action:\n${{ steps.registerts.outputs.result }}"
